# Generated by Django 3.2.5 on 2022-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('foto', models.ImageField(upload_to='fotografias')),
                ('cedula', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('certificado', models.ImageField(null=True, upload_to='certificados')),
            ],
        ),
    ]
